### ISSUE TITLE
is this what I think it is?

### ISSUE THREAD

**Issue by phette23** [cca/ezproxy_config#1]
Not really an issue. Do you want me to submit config changes as pull requests to this repo? I fully support that, makes things easier all around I think.

Also surely that config file is incomplete? Only lists one database. I have a (maybe current?) copy of the config.txt on my machine but obviously the version on the server is the best.

**Comment by mgoh** [comment]
ha you found it. 

yes this will be the way you update ezproxy from now on. it is not fully automated yet though bc i still need to push the change but its a couple steps closer.

mark
